package com.parkourrace.gam.utils

const val TETRIS_COLUMN_SIZE = 7
const val TETRIS_ROW_SIZE = 13

const val LINK_PREFERENCES_DATA_STORE = "LINK_PREFERENCES_DATA_STORE"
const val GAME_PREFERENCES_DATA_STORE = "GAME_PREFERENCES_DATA_STORE"